Repository tildeio/ember-element-helper, pull requests merged in 2023-08, with the labels that each got.

#108 Switch to `pnpm`
  .github/workflows/ci.yml
  .npmrc
  ember-element-helper/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app/config/ember-try.js
  test-app/package.json
  yarn.lock
Labels: internal

#107 Add glint support
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  README.md
  ember-element-helper/README.md
  ember-element-helper/babel.config.json
  ember-element-helper/package.json
  ember-element-helper/rollup.config.mjs
  ember-element-helper/src/helpers/element.ts
  ember-element-helper/src/index.js
  ember-element-helper/src/index.ts
  ember-element-helper/src/template-registry.ts
  ember-element-helper/tsconfig.json
  ember-element-helper/types/index.d.ts
  pnpm-lock.yaml
  test-app/app/components/element-receiver.hbs
  test-app/app/components/element-receiver.ts
  test-app/app/controllers/.gitkeep
  test-app/app/helpers/.gitkeep
  test-app/app/models/.gitkeep
  test-app/app/routes/.gitkeep
  test-app/app/templates/application.hbs
  test-app/config/ember-try.js
  test-app/ember-cli-build.js
  test-app/package.json
  test-app/tsconfig.json
  test-app/types/global.d.ts
Labels: enhancement, breaking

#110 Tell volta to use node@16
  package.json
Labels: internal

#109 Update RELEASE and CONTRIBUTING md files
  CONTRIBUTING.md
  RELEASE.md
Labels: documentation

#113 Remove reference to EmberComponent to remove the triple-slash directive
  ember-element-helper/src/helpers/element.ts
Labels: bug
